"""Official bounded classical algorithms for Tributo."""

from tributo_algorithms_classical.descriptors import (
    EXTRA_TREES_JOBLIB_DESCRIPTOR,
    EXTRA_TREES_NATIVE_DESCRIPTOR,
    LINEAR_REGRESSION_DESCRIPTOR,
    LOGISTIC_REGRESSION_DESCRIPTOR,
    RANDOM_FOREST_JOBLIB_DESCRIPTOR,
    RANDOM_FOREST_NATIVE_DESCRIPTOR,
)
from tributo_algorithms_classical.multinomial_nb_descriptor import (
    MULTINOMIAL_NB_DESCRIPTOR,
)

__all__ = [
    "EXTRA_TREES_JOBLIB_DESCRIPTOR",
    "EXTRA_TREES_NATIVE_DESCRIPTOR",
    "LINEAR_REGRESSION_DESCRIPTOR",
    "LOGISTIC_REGRESSION_DESCRIPTOR",
    "MULTINOMIAL_NB_DESCRIPTOR",
    "RANDOM_FOREST_JOBLIB_DESCRIPTOR",
    "RANDOM_FOREST_NATIVE_DESCRIPTOR",
]
